language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run coverage
env:
  - secure: "HCZlqbrcPRfxXsDj+14RuJqL4Lqx7dKF1aeQgKWpCFJeZy+bfNsByaHlLjo1b1gBW1hiOIERaDD8KnokosbE2cd9CtnsNNVoTyXSOIOWN8VFk+RN3eOVZHwOpCKIHh1jVM1ROAjNiEp7aCd+geY4wV2BeuU9/QN4upZljEozjvaN7DQTZpG0ICtBze4gJXJd6ZWbTuW95YUB3vnw7UI6ARbo9dgfWN9KSh2zTQVyC3bz8kv2JPn5sT5RIjYG25dYzKBOz1nj7vh5npdEst5KUOJd+SAefCPXEvVH4e3TDXSQccS7Wg5UcmsW4OMOS1P9BOSa1NWCyz5hxHSOCCTSeT9TiXMmTuiN+LMfowrP4r9TjhnJBlH4eeXfQR4eZ3wiVuhAIQxrtXVG8BmJv2fBjBsmHsuErtAcfMxuyKm/fDWtxzZ1ZVofZx/zypYlGUk7fMTQIKdczUb4aUKV3pWuoW47ULyVKZ/J5+tFjZYa3NfZ7Jykb7CGRbH52+nb2rUNi2E5h8KaRvv6+WRBDkhwxjZyfYOyYJgbVwurzOv1bCArZcwuWsOb5Uwymhm+b4ddM/M6L+Ap1XbQ+DCSCGLqgiQMpCGpJFsMkM8XY7OqrMBZvkDDMfmqqYTXwCMcGQd9GINwurB5IQJ0RWBgetPCZ6DdeHdD2VoWN5G2+l/6v4g="
