language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run coverage
env:
  - secure: "H3OL13uI+TSlYF/fVI8hCAen8HO0E4kMgg8RK0Sf50hkHjiFVaA4LmL7bQL5XujeJUzo8c1xSb3fB9NFHzzY9wolH+3MT0M0vXvIjcmhae9c/NMtdO3G3xMLTtWqfEisg7Png4Ja2zrIQhJe0lLDCADPV0fY1F074wzpGJPgqwi5TBh2tWrMWZhik7T871LBrfFjWiMTP2VMFgUj6untzIuywlEMVq0L6YH1z6fdoJmVPapB95eZP0a7HrlPXXVtn91Lk+Uy/6MI60DChsJYtU8mofcGYGuerWS6eC6MC0nl/sY4FIA+Jo2hpH60/orR4hge6xUrisIiydnJ1v39dZl1lIE5HeCbD186ZCufSHd2yrAaC8j2wHfGIfsWAJ5/DPTNFlBr34uwim/Sk4i0c2Uq1D8t5BIUwQWti/EbQ90A1SZOfRJo2Jr/Jv38+ERcyzEiEi9l7lxAPN9CDNkn/xpTLdY9VNfkCNZrGXGGl4Y8ppQZ5lzKG51/3VNl+frh0RoS7F8ypFPssiA3tJ9bMLPltgzbwSwD+FP2r10nEwfbkyQcLAV8GsEaj7/sIhcTDH6U2hUGh0O2knFgeImmsFi/2ZT9xmxvyqk/nydXITHrt/m3mhsAWm0jDp5gKrY45j4nTGCOoZxEq2tWsGYJPmB1X6rvEp1RVZ8vi+spoEo="
